### PR TITLE
Fix typo in Java Doc

### PR DESCRIPTION
**Pull request by Gregor-Gottschewski**
Changed a small typo in the Java Docs in `Json.java`.

### CODE REVIEW

**Comment by lukasj** [comment]
[ECA check](https://api.eclipse.org/git/eca/status/gh/jakartaee/jsonp-api/408) failed - sign [ECA](https://accounts.eclipse.org/user/eca), please. Without it, this cannot be merged. Thanks!

**Comment by Gregor-Gottschewski** [comment]
I have signed ECA. Sorry forgot to revalidate. Now the check passed successfully.

**Comment by lukasj** [comment]
thank you. One more minor thing, I forgot to mention yesterday - can you update copyright year in the header? Just change  _2021_ to _2024_ there, on line 2.

**Comment by Gregor-Gottschewski** [comment]
No problem. I've updated it.

**Review by lukasj — APPROVED** [review]
Thank you

**Pull request merged**
